-- Report reason 컬럼 길이 확장 (30 → 40)
-- SHOP_REPORT_INAPPROPRIATE_CONTENT(33자), SHOP_SUGGESTION_WRONG_LOCATION_HINT(35자) 지원을 위해 필요
ALTER TABLE reports ALTER COLUMN reason TYPE VARCHAR(40);

-- 기존 SHOP 타입 신고 데이터 마이그레이션
-- 1. 문제 신고 성격의 reason은 SHOP_REPORT 타입으로
UPDATE reports
SET target_type = 'SHOP_REPORT',
    reason = CASE reason
        WHEN 'SHOP_INAPPROPRIATE' THEN 'SHOP_REPORT_INAPPROPRIATE'
        WHEN 'SHOP_INAPPROPRIATE_CONTENT' THEN 'SHOP_REPORT_INAPPROPRIATE_CONTENT'
        WHEN 'SHOP_INAPPROPRIATE_HINT' THEN 'SHOP_REPORT_INAPPROPRIATE_HINT'
        WHEN 'SHOP_DUPLICATE' THEN 'SHOP_REPORT_DUPLICATE'
        WHEN 'SHOP_OTHER' THEN 'SHOP_REPORT_OTHER'
        ELSE reason
    END
WHERE target_type = 'SHOP'
  AND reason IN ('SHOP_INAPPROPRIATE', 'SHOP_INAPPROPRIATE_CONTENT', 'SHOP_INAPPROPRIATE_HINT', 'SHOP_DUPLICATE', 'SHOP_OTHER');

-- 2. 정보 수정 제안 성격의 reason은 SHOP_SUGGESTION 타입으로
UPDATE reports
SET target_type = 'SHOP_SUGGESTION',
    reason = CASE reason
        WHEN 'SHOP_WRONG_ADDRESS' THEN 'SHOP_SUGGESTION_WRONG_ADDRESS'
        WHEN 'SHOP_WRONG_LOCATION_HINT' THEN 'SHOP_SUGGESTION_WRONG_LOCATION_HINT'
        WHEN 'SHOP_CLOSED' THEN 'SHOP_SUGGESTION_CLOSED'
        WHEN 'SHOP_WRONG_HOURS' THEN 'SHOP_SUGGESTION_WRONG_HOURS'
        WHEN 'SHOP_WRONG_PAYMENT' THEN 'SHOP_SUGGESTION_WRONG_PAYMENT'
        WHEN 'SHOP_FALSE_INFO' THEN 'SHOP_SUGGESTION_OTHER'
        ELSE reason
    END
WHERE target_type = 'SHOP'
  AND reason IN ('SHOP_WRONG_ADDRESS', 'SHOP_WRONG_LOCATION_HINT', 'SHOP_CLOSED', 'SHOP_WRONG_HOURS', 'SHOP_WRONG_PAYMENT', 'SHOP_FALSE_INFO');

-- 3. 분류되지 않은 나머지 SHOP 타입은 SHOP_REPORT_OTHER로 변환 (안전장치)
UPDATE reports
SET target_type = 'SHOP_REPORT',
    reason = 'SHOP_REPORT_OTHER'
WHERE target_type = 'SHOP';
